language: node_js
sudo: required
before_install:
- docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"

install: true


script:
- docker build -t dto80/htmltest
- docker push dto80/htmltest
after_success:
- docker run -p 8888:80 -h $HOST_NAME dto80/htmltest -d

service: docker
env:
  global:
  - secure: e3RVUwGxMUyPNzp6607mIPwF04IcfTh5DiJre+CGr+w8x/uRooYyrmg8kh60W8eMrehhl+CuSoSNgga0H3F81X+Y/MFAPcrZGVvKvSLhNHmoCz4lag8q5ltdE0wy3wIwSLq0Ly3FwEQGcAgjHJ8W/OmO53dzxglbS14PBj/0RL0gKpGEHrPz2k91IZu2njZFMkrujrKu4gg0gpWVeGPd51F0SItBr9Ql2l4FB0iluyBhlUHcAxhaUb181sgm5MWbpUQKQnKSz0kA0Xh0B30cqN2cq2WssTU6KiHF3QjrTl+OiTzTOdDW7erzfINBjpu68cRstHOX5A2uytTNjvlmkW5RpTfJyXJfeBtLL3wi8S29H+RmRqgn18OCteZONb2oDSWo+dRVOQNUlNNiG+w3gQMmaMQdc+TB80hU1LRN7YLZJG5SjHXWETSYfhg1NBRAYSXWimJc4qY0ZFj3xDvF5Pt1Y9e7BPYeeQBggBWRqB1r8bDyu9tmgPqOcQPo/+kFovKbcyhMKj/NXLe8KottBTbGqb9ePA4KpQHQVSZ9QMiZZuqOhhaiWcs0E2WblJ2DJoqNpYhuN5nhMO/+kf0EB5r6awIm757HELWUaA76tj6gFYNUq/VKtiRJ0rNtSz203rJ8cMF8ArTjEXvhZhzE0jtgB/djD1+gUUmQ3IaGmUY=
  - secure: sLelLAu5fE1Z55PFOYhmSJvliwGO+YBYgR6xaMSkjKP1tL+rhk4oZZmXKAmazK6a/OIpnMQCYiWyMjaV9H2/NJJQ71p4geXzEcCZTxLenbROwuTHL1xS1HgSy1wpj8gdrJbMXxnQlOqW6AiSX1gdXIh07r4V2PZpkHBhFxm4psI6JaO5Ro0rsXP6UEZ6vdyAs+VqlP4dsJGWphVcqMQcHSrj0Ul50SDFsLcdTZ2g4yrkFV3I9AFVoKw/FWtLNPiCygdBaCziZk57r3wYNVlX4iqnhzAdinloqFhxQCSxPTVy0/coZFR6FYQa1D939+uiFqaSY7uvrIea/T3aE6CKMRpT9YNYJAjlHR5k5jkL/hfhPVznVWnniMVpK5HQRCSOlm4VntdiIFhKtWT4rjlAvqz5SvFsI9Pscjy4dn6SMNbUIPkB7gzHGHxseOYpwuXj1c0IVjoObe3DbASi0E/Uy9RrE894oAsEztR5YLcspHaQluG+Ap385hldyVkF3XjLdSQYgjwMZcSKKtwWtlm33qbuVBicBxliy2xpwkFTdHxNArl/PkGC2WFVlnfEUrNUQz5ryUU6n+dAR5dfX0TOrw79ZH/vQbNq/2wzKQbf4TQZEy+Afh/sp6P+iNeZlIXB870TuYUR5088nl44+ox57zYC25Ezp+Rs4iRMHhajId8=
  - secure: pvw4aA5GegntC09+BoH7l4buhAP4tzbdoWIq1KX1712ATcuEsYeH7mTOiIHMNiigo3YFxnpMnqSrfl1Ruld7DEj4YUFYB6Ov1nbjO/jWSymT5te8eDL22Sietw5wqxkQXu56gYwK1ATVVqTjjZu/ci8jM3c+1G9kBGtojIKBAiVpVIN1y5Z5LqX2SiaYz9EhwmCdDxyLd2BWq0UTcs//1wBbheXO8JAys823lXzeMlkd0+WRpsCjU0IuxjbA2lN2QSGilzjLwOoKjG/mnHnBfparnkMgGdSCWUKAhMfC0J7jpbbesLl52wAz3XrUkhnc0H5Vee31fT7mLSjVa4FAV3qd7pKEMJFfWWzD4Kc0bF4VeM17feSRdkrrhjYwzYE7cOlJh0MX8bZDuX9pXNPiFGXnM0PjsO5cBp257g8CmR76FlU4M9b+VIhfC6HgRyjT525ehblEbdQW7EiZ3JVzY7yqOvfcH0yNEgmxZ8a75KoxyUTpUwzYLKRu/18nK8R8LUUidTS3oL1q9OVOpiTnayMso65JvHVHJed1RdANv8uOyYWZRgvcU0/s2wrfp8McJjhdoatA8LWAfxASeZS9DNVbwe/f3e4hlkoebnJqlVHK9FqieZav38CliJx51hF0RuALTvGFr7BjGOmHoqfJgdqU1GcVTnzAyXL6F9IknyU=